ALL_GUNS_KNIVES = [
    # Guns
    'AK-47',
    'AUG',
    'AWP',
    'DESERT EAGLE',
    'DUAL BERETTAS',
    'FAMAS',
    'FIVE-SEVEN',
    'G3SG1',
    'GALIL AR',
    'GLOCK-18',
    'M249',
    'M4A1-S',
    'M4A4',
    'MAC-10',
    'MAG-7',
    'MP7',
    'MP9',
    'NEGEV',
    'NOVA',
    'P2000',
    'P250',
    'P90',
    'PP-BIZON',
    'SCAR-20',
    'SG 553',
    'SSG 08',
    'SAWED-OFF',
    'TEC-9',
    'UMP-45',
    'USP-S',
    'XM1014',
    'CZ75-AUTO',
    'R8 REVOLVER',
    'MP5-SD',
    # Knives
    'BAYONET',
    'BOWIE KNIFE',
    'BUTTERFLY KNIFE',
    'CLASSIC KNIFE',
    'FALCHION KNIFE',
    'FLIP KNIFE',
    'GUT KNIFE',
    'HUNTSMAN KNIFE',
    'KARAMBIT',
    'M9 BAYONET',
    'NAVAJA KNIFE',
    'NOMAD KNIFE',
    'PARACORD KNIFE',
    'SHADOW DAGGERS',
    'SKELETON KNIFE',
    'STILETTO KNIFE',
    'SURVIVAL KNIFE',
    'TALON KNIFE',
    'URSUS KNIFE',
]
